openapi: 3.0.1
info:
  title: Supplier-MS - OpenAPI 3.0
  description: |-
    This is an API for a Fake Supplier to deliver the FIAP university microservices project
  version: v1
tags:
- name: Supplier
  description: Operations about Supplier (w/ Import and Export Requests)


paths:
  /api/Supplier:
    get:
      tags:
        - Supplier
      summary: Get Supplier data
      description: List Supplier data
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supplier'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supplier'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supplier'
    post:
      tags:
        - Supplier
      summary: Add to requested Supplier
      description: Successful Boolean on Return
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Supplier'
          text/json:
            schema:
              $ref: '#/components/schemas/Supplier'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Supplier'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Supplier'
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
            text/json:
              schema:
                $ref: '#/components/schemas/Supplier'
  /api/Supplier/{id}:
    get:
      tags:
        - Supplier
      summary: Get specific Supplier data
      description: Supplier data list
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Supplier'
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
            text/json:
              schema:
                $ref: '#/components/schemas/Supplier'
    put:
      tags:
        - Supplier
      summary: Change specific Supplier
      description: Successful Boolean on Return
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Supplier'
          text/json:
            schema:
              $ref: '#/components/schemas/Supplier'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Supplier'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Supplier
      summary: Delete the requested Supplier
      description: Successful boolean on Supplier deletion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/Supplier/Import/{quantity}:
    post:
      tags:
        - Supplier
      summary: Request Import of Products
      description: Product Import Request
      parameters:
        - name: quantity
          in: header
          schema:
            type: integer
            format: int32
        - name: quantity
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          text/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Supplier'
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
            text/json:
              schema:
                $ref: '#/components/schemas/Supplier'
  /api/Supplier/Export/{quantity}:
    post:
      tags:
        - Supplier
      summary: Request Export of Products
      description: Request Export
      parameters:
        - name: quantity
          in: header
          schema:
            type: integer
            format: int32
        - name: quantity
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          text/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Supplier'
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
            text/json:
              schema:
                $ref: '#/components/schemas/Supplier'
components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        price:
          type: number
          format: double
        quantity:
          type: integer
          format: int32
        createDate:
          type: string
          format: date-time
      additionalProperties: false
    Supplier:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        createDate:
          type: string
          format: date-time
      additionalProperties: false
